version: "3.8"
services:
  mongo-service-tweekalytics:
    image: "mongo"
    container_name: "mongo-service-tweekalytics"
    volumes:
      - mongo-service-tweekalytics:/data/db
    ports:
      - "27017:27017"

  kafka-service-tweekalytics:
    container_name: "kafka-service-tweekalytics"
    image: bitnami/kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  mongo-service-tweekalytics:
  kafka-service-tweekalytics: